name: Build and Push image to Docker Hub

on:
  push:
    branches:
      - 'php-vim'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Scripts
        run: |
          docker build -t app .
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin 
          docker tag app pc018/php-vim
          docker push pc018/php-vim

      
