name: Build and Push image to Docker Hub

on:
  push:
    branches:
      - 'php-vim'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push: pc018/php-vim:tagname
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
#           push: true
          tags: user/app:latest
